### ISSUE TITLE
--tag

### ISSUE THREAD

**Issue by rhwillms** [zzamboni/enwrite#11]
It seems that enwrite.rb has some code that disallows --tag:

lines 130-132
    if not (options.notebook or options.searchexp or options.forceauth)
      error "You have to specify at least one of --notebook, --search or --auth"
      exit(1)

Thus I couldn't download tags.

My installation of ruby is broken vis-a-vis a requirement of the Rakefile, so I couldn't fix this myself.

**Comment by zzamboni** [comment]
Hi @rhwillms, thanks for your comment. This is a design decision: `--tag` is meant to be used together with `--notebook`, to make it easy to do the most common case: publish all the notes with a certain tag from a given notebook.

If you want to choose all the notes with a given tag, regardless of the notebook, you can use `--search` with a search expression of the form "tag:<sometag>", or any other valid search expression (see https://dev.evernote.com/doc/articles/search_grammar.php for the reference).

Hope this helps, and thanks for trying out enwrite!
