### ISSUE TITLE
 The 'base_dir' option of the Hugo plugin must be set!

### ISSUE THREAD

**Issue by andreabisello** [zzamboni/enwrite#15]
i installed the plugin.
i authenticated with evernote.
i put the token.
something goes wrong.
this is the log

> Welcome to enwrite's Evernote authentication.
> 
> Please open the following URL:
> https://www.evernote.com/OAuth.action?oauth_token=zzamboni-XXXXXXXXXXXX.XXXXXXXXXXX
> 
> Once you authenticate you will be redirected to
> a page in the zzamboni.org domain that will show you an authentication verifier
> token. Please enter that token now.
> > XXXXXXXXXXXXXX
> Thank you! Your access token is the following string:
> S=s77:U=83615c:E=16cc2b4bbea:C=1656b038f00:P=185:A=zzamboni-2648:V=2:H=e6373a8982ac3ee2faacf173106e0d2d
> 
> I can store the token for you in the config file (C:/Users/andrea.bisello/.enwrite.config),
> then enwrite will use it automatically in the future.
> Would you like me to do that for you now (Y/n)? Y
> Token stored.
> C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/evernote-thrift-1.25.2/lib/thrift/protocol/base_protocol.rb:254: warning: constant ::Fixnum is deprecated
> C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/evernote-thrift-1.25.2/lib/thrift/protocol/base_protocol.rb:294: warning: constant ::Fixnum is deprecated
> 2018-08-24 10:18:55 ora legale Europa occidentale 2018 Enwrite [INFO]: Checking updated Evernote contents...
> 2018-08-24 10:18:55 ora legale Europa occidentale 2018 Enwrite [ERROR]: The 'base_dir' option of the Hugo plugin must be set!
> 2018-08-24 10:18:55 ora legale Europa occidentale 2018 Enwrite [INFO]: Found note 'Benvenuto in Evernote'
> Traceback (most recent call last):
>         7: from C:/Ruby25-x64/bin/enwrite:23:in `<main>'
>         6: from C:/Ruby25-x64/bin/enwrite:23:in `load'
>         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/enwrite-0.2.4/bin/enwrite:10:in `<top (required)>'
>         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/enwrite-0.2.4/lib/enwrite.rb:279:in `run'
>         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/enwrite-0.2.4/lib/enwrite.rb:279:in `each'
>         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/enwrite-0.2.4/lib/enwrite.rb:284:in `block in run'
>         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/enwrite-0.2.4/lib/output/hugo.rb:147:in `output_note'
> C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/enwrite-0.2.4/lib/output/hugo.rb:147:in `chdir': no implicit conversion of nil into String (TypeError)
>

**Comment by zzamboni** [comment]
Hi @abioneperhobby - you need to use the `-o` option to specify the base directory of your Hugo site:
```
    -o, --output-dir OUTDIR          Base dir of hugo output installation
```
